### PR TITLE
Added a Gemfile, and referenced the quasi-official counterparty_ruby gem...

### PR DESCRIPTION
**Pull request by brighton36**
... instead of curl to fetch

issuances. Cleaned the code up slighty to be more compact, and switched the connection from the
unsupported counterwallet servers, to the supported vennd.io public servers.

### CODE REVIEW

**Comment by makevoid** [comment]
:D Thanks, oh I didn't know there was a ruby library to check token availability, cool!

**Comment by brighton36** [comment]
It's a wrapper around the whole API. I'm currently working through transaction signing, but it's very usable for everything you'd want from the official counterpartyd rpc server.

**Comment by makevoid** [comment]
I liked my javascript-like way of coding ruby but you took the effort to actually clean it so ok, I'm merging this in and updating the readme

Also I'm surprised that almost all the tokens that I put in the default wordlist (that I hand picked by the 1000 most searched word in google in 2013 I think) - are now registered counterparty tokens :D

**Comment by makevoid** [comment]
also I think that vend.io it's a bit slower than the original counterparty endpoint or maybe it's my current connection

**Comment by makevoid** [comment]
https://github.com/makevoid/counterparty_token_checker/commit/14323e8d089d8c5eb88583b3fc448983e2afce18 I added some installation instructions so even if you don't know ruby it should be able to set-up

If more people register counterparty token then more XCP (and BTC) are burned and there's more investment in the field - also maybe people will actually make an use of them or resell them for other tokens/*coins

**Comment by brighton36** [comment]
Go back to the javascript style by all means if you like that! I was mostly just showing you that there's a decent lib for this. As for the speed, I actually found that vend.io was pretty quick for me, and thought you'd appreciate that :). The better way to do this is probably to submit a filter of 10 to 30 terms at a time, and seeing if they match. I thought of doing it that way for you, but I wasn't sure if you'd be interested. As for the squatting, that's very common right now, the assets are way under priced IMO.

**Comment by makevoid** [comment]
Haha nah it was mostly a joke, the new ruby block syntax feels a lot like I'm writing JS or coffeescript. 

Anyway I looked into the  lib and I like how you use define_method (and not method missing) for metaprogramming to achieve compatibility/callability 1:1 to the counterparty api! Very cool! I hope to contribute to it in the future!

**Pull request merged**
